---
title: "Chicken Weights Analysis"
author: "*Wejdan Saleh*"
date: "*03/09/2020*"
output: html_document

---


```{r setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(rio)
library(Hmisc)
library(knitr)
library(DT)
library(dplyr)

#library(shiny)

```

## Descriptive Statistics

````{r output="asis",  echo=FALSE}
chickwts  %>%
  group_by(feed) %>%
  summarise(n = length(feed), Average = mean(weight) ,SD= sd(weight), .groups = "drop" ) %>%
  datatable()
```

## Plots

````{r, echo=FALSE}
ggplot(chickwts, aes(feed,weight)) +
  geom_boxplot()
```


````{r, echo=FALSE}
ggplot(chickwts, aes(feed,weight)) +
     geom_jitter(width = 0.15) +
     stat_summary(fun.data = mean_sdl, 
                  fun.args = list(mult = 1),
                col = "red")
```


## Inferential Statistics
The one-way ANOVA summary:

```{r output="asis", echo=FALSE}

   chickwts_lm <- lm(weight ~ feed , data =  chickwts)
   #chickwts_lm
 
     anova(chickwts_lm) %>%
       kable()

```

 Tukey’s Post-hoc test:
 
 
```{r output="asis", echo=FALSE}

   chickwts_a <- aov(chickwts_lm) 
   tukeyTest <- TukeyHSD((chickwts_a)) 
 #  as.data.frame(tukeyTest[1:1]) %>%
   as.data.frame(tukeyTest$feed)%>%
    
   datatable()
```
 





